k in K
a in A

act ::= τ | a | 'a

f ::= a/a | a/a, f
channels ::= a | a, channels
L ::= a | {channels}

P ::= 0
    | (P)
    | c. P
    | k
    | P + P
    | P | P
    | P[f]
    | P \ L

π ::= P
    | k = P; π
