n in ℕ
k in K
x in Var
a in A

abop ::= + | - | * | / | mod

e ::= n
    | (e)
    | x
    | e abop e

bbop ::= = | ≠ | < | > | ≤ | ≥

b ::= true | false
    | (b)
    | not b
    | b and b
    | b or b
    | e bbop e

act ::= τ | a(x) | 'a(e)

args ::= ε
       | e
       | e, args
f ::= ε
    | a/a
    | a/a, f
channels ::= a | a, channels
L ::= a
    | {}
    | {channels}

P ::= 0
    | (P)
    | act. P
    | k
    | k(args)
    | if b then P
    | P + P
    | P | P
    | P[f]
    | P \ L

params ::= ε
         | x
         | x, params
π ::= P
    | k = P; π
    | k(params) = P; π
